# Generated by Django 3.0 on 2019-12-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_auto_20191214_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='password',
            field=models.CharField(max_length=64, verbose_name='비밀번호'),
        ),
        migrations.AlterField(
            model_name='fcuser',
            name='username',
            field=models.CharField(max_length=12, verbose_name='사용자명'),
        ),
    ]
